name: first-flow
on: [push]
jobs:
  First-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "hello there"
      - name: run-commands
        run: |
          npm -v
          node -v
  BashCommand:
    runs-on: windows-latest
    needs: [First-job]
    steps:
      - name: first-bash-BashCommand
        run: pwd
        shell: cmd
