name: first-flow
on: [push]
jobs:
  First-job:
    runs-on: ubuntu-latest
    steps:
      - name: first steps
        run: echo "hello there"
      - name: run-commands
        run: |
          npm -v
          node -v
